name: movie
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.2.1
  media_kit: ^1.1.11 # Primary package.
  media_kit_video: ^1.2.5 # For video rendering.
  media_kit_libs_video: ^1.0.5
  flutter_dotenv:
  flutter_launcher_icons:
  hive:
  hive_flutter:
  path_provider:

  cupertino_icons: ^1.0.2
  dio: ^5.4.1
  toast: ^0.3.0
  html:
  extended_image: ^8.2.0
  test: ^1.24.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/icon.jpg
